### ISSUE TITLE
Null outputs for some forms stemmed with lemmatization turned on

### ISSUE THREAD

**Issue by mcelvg** [coltekin/TRmorph#15]
After compiling *stem.fst* with `STEMMER_LEMMATIZE` set to 1, we get what looks like a null result ("+?") for certain inputs. 

It appears that the "+?" output happens regularly with infinitival verbs, i.e. forms that already end with "-mek" or "-mak". (I'm not a Turkish speaker, but I did try it on this [list of verbs](https://en.wikibooks.org/wiki/Turkish/List_of_Verbs).)

E.g., 

```
$ echo "kızartmak" | flookup stem10.fst 
kızartmak
kızar<V>
kızartmak
kızart<V>

$ echo "kızartmak" | flookup stem11.fst
kızartmak
+?

$ echo "ölmek" | flookup stem10.fst 
ölmek
öl<V>

$ echo "ölmek" | flookup stem11.fst 
ölmek
+?

$ echo "çalışmak" | flookup stem10.fst 
çalışmak
çalış<V>

$ echo "çalışmak" | flookup stem11.fst
çalışmak
+?
```

The only difference between *stem10.fst* and *stem11.fst* above is the `STEMMER_LEMMATIZE` setting.

It seems that in most (maybe all?) of these cases the *stem11.fst* output would otherwise be the same as the input. Perhaps the “+?” output is expected behavior. Could you clarify? 

Thanks.

**Comment by coltekin** [comment]
Thanks for the report (took me a while to look at it, still recovering from a long holiday).

`STEMMER_LEMMATIZE` only appends the _-mek/-mak_ to the end of the lemmas of the verbs (which produces the citation form of the verbs as used in the dictionaries). The setting does not affect anything else.

The above behavior (not lemmatizing the infinitive verbs) is a bug. I have  a fix, I will push it after a bit of testing.
